### ISSUE TITLE
New Tech Bulletin Button

### ISSUE THREAD

**Issue by robchar** [stellaballa/ProsisProUpdate#1]
Hi Stella,
@stellaballa 
@SagarPC 
@stevefox3781

When you click the new tech bulletin button (thumb tack) and then click the "Return to Search Result" button it should take you back to the previous screen like when you click the original tech bulletin button (thumb tack). Right now it takes you all the way back to the engine search screen.

![PROSIS #1](https://user-images.githubusercontent.com/26470619/89053671-32527b00-d31d-11ea-918c-db0f2270df3d.png)
![PROSIS#2](https://user-images.githubusercontent.com/26470619/89053690-38e0f280-d31d-11ea-911e-fe3bd8a66c1a.png)

**Comment by stellaballa** [comment]
@SagarPC  can we update the link if customers are coming from the engine spec, the link should be "Return to Engine" And it will take the to the engine spec.

**Comment by stellaballa** [comment]
@SagarPC  please let me know if this has been completed.

**Comment by robchar** [comment]
This is also working now, thank you.
@stellaballa 
@SagarPC 
@stevefox3781
