### ISSUE TITLE
Casting Search is missing

### ISSUE THREAD

**Issue by robchar** [stellaballa/ProsisProUpdate#3]
Hi Stella,

@stellaballa 
@SagarPC 
@stevefox3781

All of the new Advance Search features have been added but the Advance Search casting look up seems to be missing. The top image is the test site and the bottom image is the current PROSIS.

![PROSIS#3](https://user-images.githubusercontent.com/26470619/89065525-7c455c00-d331-11ea-960e-40144f80339a.png)
![PROSIS#4](https://user-images.githubusercontent.com/26470619/89065543-82d3d380-d331-11ea-95b6-c87a3255a9f6.png)

**Comment by stellaballa** [comment]
@SagarPC  can we add the casting search back in. Add a red button next to "Search by Component & Size" called "Casting Search"

**Comment by SagarPC** [comment]
@robchar We added casting number search. Please see below image for reference.

![image](https://user-images.githubusercontent.com/31076567/89781497-132fc680-db31-11ea-8292-e42516d14613.png)

**Comment by robchar** [comment]
This is working now, thank you.

@stellaballa 
@SagarPC 
@stevefox3781
