### ISSUE TITLE
Add Blank Editable Prosis Pro Sheets

### ISSUE THREAD

**Issue by stevefox3781** [stellaballa/ProsisProUpdate#4]
Please add this under Worksheets, Download Worksheets and title Blank Prosis Pro. This is one document but if you think we need to break it out into each section (head, block, crank, rod, cam, torqu) I can do that as well. 

[Editable Blank Engine Spec Sheets.pdf](https://github.com/stellaballa/ProsisProUpdate/files/5018188/Editable.Blank.Engine.Spec.Sheets.pdf)

**Comment by stellaballa** [comment]
@SagarPC  can you take a look at the PDF and make the Overview section editable in the PDF?

**Comment by SagarPC** [comment]
@stevefox3781  can you please send head, block, crank, rod, cam, torque pdf so we can use that?

**Comment by stevefox3781** [comment]
@Sagar Jagdish<mailto:sagar@partsconnect.us> There are a couple of spots in the cylinder head section that did not covert to editable sections. All the others seem to be fine. Hope this helps and what you are looking for.

Need anything else, let me know.

Steve Fox
AERA Vice President/Tech Specialist
(P) 815-526-7348
(F) 888-329-2372
www.aera.org

**Comment by SagarPC** [comment]
@stevefox3781 We updated the file on stage and provide a download option for each. Also made header editable for all PDF.

![image](https://user-images.githubusercontent.com/31076567/89658193-dcb53a00-d8eb-11ea-82f7-49b94a996160.png)

**Comment by stevefox3781** [comment]
Great - thank you!
