### ISSUE TITLE
Tech Procedure short cut font looks different than the other numbers

### ISSUE THREAD

**Issue by robchar** [stellaballa/ProsisProUpdate#5]
Hi,

@stellaballa 
@SagarPC 
@stevefox3781 

The new short cut for the tech procedure under the wrench looks different than the other numbers, it almost looks like it needs to be bold. I have attached a sample.

![PROSIS #3](https://user-images.githubusercontent.com/26470619/89834634-dcee4900-db28-11ea-8a2e-d77f734049ba.png)

Thanks
Rob

**Comment by SagarPC** [comment]
@robchar We fixed this

![image](https://user-images.githubusercontent.com/31076567/90124045-65fdbe00-dd7d-11ea-9068-c615acbaee05.png)

**Comment by robchar** [comment]
Looks to be working now, thanks.

@stellaballa 
@SagarPC 
@stevefox3781
